### ISSUE TITLE
Error Message "Could not launch browser" when starting crawler of quickstart guide

### ISSUE THREAD

**Issue by rgeissen** [USCDataScience/sparkler#64]
17/01/28 15:02:03 INFO Executor: Running task 0.0 in stage 1.0 (TID 2)
17/01/28 15:02:03 INFO Executor: Running task 1.0 in stage 1.0 (TID 3)
17/01/28 15:02:03 INFO CacheManager: Partition rdd_3_0 not found, computing it
17/01/28 15:02:03 INFO CacheManager: Partition rdd_3_1 not found, computing it
17/01/28 15:02:03 INFO ShuffleBlockFetcherIterator: Getting 2 non-empty blocks out of 2 blocks
17/01/28 15:02:03 INFO ShuffleBlockFetcherIterator: Getting 2 non-empty blocks out of 2 blocks
17/01/28 15:02:03 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 5 ms
17/01/28 15:02:03 INFO ShuffleBlockFetcherIterator: Started 0 remote fetches in 5 ms
17/01/28 15:02:03 INFO PluginService$: Felix Configuration loaded successfully
17/01/28 15:02:03 INFO FetcherJBrowserActivator: Activating FetcherJBrowser Plugin
17/01/28 15:02:03 INFO RegexURLFilterActivator: Activating RegexURL Plugin
Bundle Found: org.apache.felix.framework
Bundle Found: fetcher.jbrowser
Bundle Found: urlfilter.regex
[2017-01-28T15:02:04.134] java.lang.NoClassDefFoundError: com/sun/webkit/network/CookieManager
[2017-01-28T15:02:04.134] 	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.main(JBrowserDriverServer.java:74)
[2017-01-28T15:02:04.135] Caused by: java.lang.ClassNotFoundException: com.sun.webkit.network.CookieManager
[2017-01-28T15:02:04.135] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[2017-01-28T15:02:04.135] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[2017-01-28T15:02:04.135] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[2017-01-28T15:02:04.135] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[2017-01-28T15:02:04.135] 	... 1 more
[2017-01-28T15:02:04.359] java.lang.NoClassDefFoundError: com/sun/webkit/network/CookieManager
[2017-01-28T15:02:04.359] 	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.main(JBrowserDriverServer.java:74)
[2017-01-28T15:02:04.359] Caused by: java.lang.ClassNotFoundException: com.sun.webkit.network.CookieManager
[2017-01-28T15:02:04.359] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[2017-01-28T15:02:04.359] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[2017-01-28T15:02:04.359] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[2017-01-28T15:02:04.359] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[2017-01-28T15:02:04.359] 	... 1 more
[2017-01-28T15:02:04.368] java.lang.NoClassDefFoundError: com/sun/webkit/network/CookieManager
[2017-01-28T15:02:04.369] 	at com.machinepublishers.jbrowserdriver.JBrowserDriverServer.main(JBrowserDriverServer.java:74)
[2017-01-28T15:02:04.369] Caused by: java.lang.ClassNotFoundException: com.sun.webkit.network.CookieManager
[2017-01-28T15:02:04.369] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[2017-01-28T15:02:04.369] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[2017-01-28T15:02:04.369] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[2017-01-28T15:02:04.369] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[2017-01-28T15:02:04.369] 	... 1 more
17/01/28 15:02:04 ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 2)
org.openqa.selenium.WebDriverException: Could not launch browser.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'osboxes', ip: '192.168.178.134', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-514.el7.x86_64', java.version: '1.8.0_121'
Driver info: driver.version: JBrowserDriver

**Comment by karanjeets** [comment]
@rgeissen 
Thanks for reporting this issue. Looks like JBrowserDriver is creating a problem. Can you please look into this issue - https://github.com/MachinePublishers/jBrowserDriver/issues/186
Please let us know if it works.

**Comment by thammegowda** [comment]
@rgeissen Welcome to Sparkler!
We haven't tested Jbrowser setup with sparkler on archlinux. 
Thanks for reported it. 
It seems `com.sun.*` packages are not available to felix bundles - try tweaking this file:  https://github.com/USCDataScience/sparkler/blob/master/conf/felix-config.properties#L32
 

Alternatively, you may consider the docker build w/ ubuntu 16.04 : 

https://github.com/USCDataScience/sparkler/wiki/Build-and-Deploy/_compare/0a2728c%5E...0a2728c
https://github.com/USCDataScience/sparkler/wiki/Build-and-Deploy#docker-build

please pull latest changes from master (I just now made few changes to the docker docker file)

**Comment by rgeissen** [comment]
I tried to follow the docker path but unfortunately I am getting the following error now:

The following NEW packages will be installed:
  ca-certificates-java dbus-x11 fontconfig fontconfig-config fonts-dejavu-core
  fonts-dejavu-extra gconf-service gconf-service-backend gconf2 gconf2-common
  hicolor-icon-theme i965-va-driver libaacs0 libasyncns0 libatk1.0-0
  libatk1.0-data libavahi-client3 libavahi-common-data libavahi-common3
  libavahi-glib1 libavcodec-ffmpeg56 libavformat-ffmpeg56 libavutil-ffmpeg54
  libbdplus0 libbluray1 libbonobo2-0 libbonobo2-common libcairo2 libcanberra0
  libcrystalhd3 libcups2 libdatrie1 libdrm-amdgpu1 libdrm-intel1
  libdrm-nouveau2 libdrm-radeon1 libdrm2 libelf1 libflac8 libfontconfig1
  libgconf-2-4 libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgif7
  libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa libgme0 libgnome-2-0
  libgnome2-common libgnomevfs2-0 libgnomevfs2-common libgomp1 libgraphite2-3
  libgsm1 libgtk2.0-0 libgtk2.0-bin libgtk2.0-common libharfbuzz0b libjbig0
  libjpeg-turbo8 libjpeg8 libjson-c2 liblcms2-2 libllvm3.8 libltdl7
  libmodplug1 libmp3lame0 libnspr4 libnss3 libnss3-nssdb libnuma1 libogg0
  libopenjfx-java libopenjfx-jni libopenjpeg5 libopus0 liborbit-2-0
  liborc-0.4-0 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0
  libpciaccess0 libpcsclite1 libpixman-1-0 libpulse0 libschroedinger-1.0-0
  libshine3 libsnappy1v5 libsndfile1 libsoxr0 libspeex1 libssh-gcrypt-4
  libswresample-ffmpeg1 libtdb1 libthai-data libthai0 libtheora0 libtiff5
  libtwolame0 libtxc-dxtn-s2tc0 libva1 libvdpau1 libvorbis0a libvorbisenc2
  libvorbisfile3 libvpx3 libwavpack1 libwebp5 libwrap0 libx11-xcb1 libx264-148
  libx265-79 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0
  libxcb-render0 libxcb-shm0 libxcb-sync1 libxcomposite1 libxcursor1
  libxdamage1 libxfixes3 libxi6 libxinerama1 libxrandr2 libxrender1
  libxshmfence1 libxslt1.1 libxtst6 libxvidcore4 libxxf86vm1 libzvbi-common
  libzvbi0 mesa-vdpau-drivers openjdk-8-jre openjdk-8-jre-headless openjfx
  psmisc sound-theme-freedesktop tcpd va-driver-all vdpau-driver-all
  vdpau-va-driver
0 upgraded, 145 newly installed, 0 to remove and 4 not upgraded.
Need to get 84.2 MB of archives.
**After this operation, 411 MB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
The command '/bin/sh -c apt install --fix-missing openjfx  # needed by the Jbrowser' returned a non-zero code: 1**
rgeissen@ubuntu:~/sparkler$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                          PORTS               NAMES
5127f7afe280        8b76a95808ef        "/bin/sh -c 'apt i..."   About a minute ago   Exited (1) About a minute ago  

Any idea on how to proceed?

**Comment by thammegowda** [comment]
Oh! I missed something here. Thank you very much for reporting this.

Please pull the latest code from `master` branch and try again. 
If you are wondering why docker has stopped 57c811c0  : 

`RUN apt install --fix-missing openjfx` should be changes to  `RUN apt install -y openjfx`  in the `Dockerfile`

**Comment by thammegowda** [comment]
This issue has been resolved.

Feel free to reopen this issue if you face it again.
