### ISSUE TITLE
Running iterations more than one in crawl gives null pointer exceptions sometimes. 

### ISSUE THREAD

**Issue by SHASHANK-PRO-05** [USCDataScience/sparkler#92]
Ran this command: java -jar sparkler-app/target/sparkler-app-0.1-SNAPSHOT.jar crawl -id sjob-1488053397220 -i 2

Got Exceptions of Null Pointer: 
2017-02-27 14:20:25 WARN  ParseFunction$:63 [Executor task launch worker-4] - 
java.lang.NullPointerException
	at edu.usc.irds.sparkler.pipeline.ParseFunction$.apply(ParseFunction.scala:55)
	at edu.usc.irds.sparkler.pipeline.ParseFunction$.apply(ParseFunction.scala:35)
	at edu.usc.irds.sparkler.pipeline.FairFetcher.next(FairFetcher.scala:59)
	at edu.usc.irds.sparkler.pipeline.FairFetcher.next(FairFetcher.scala:28)
	at scala.collection.Iterator$$anon$12.next(Iterator.scala:444)
	at org.apache.spark.storage.MemoryStore.unrollSafely(MemoryStore.scala:285)
	at org.apache.spark.CacheManager.putInBlockManager(CacheManager.scala:171)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:78)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by karanjeets** [comment]
@SHASHANK-PRO-05 
Thanks for reporting this issue. This should be fixed in PR #90 . I will merge it with the master soon.

Are you getting this error while using jBrower Fetcher in Sparkler?

**Comment by SHASHANK-PRO-05** [comment]
@karanjeets 
I will help you reproduce this bug. 
I injected four URLs in Solr, which were 
http://nutch.apache.org/
http://tika.apache.org/
https://github.com/USCDataScience/sparkler/wiki/Build-and-Deploy
https://www.youtube.com/

Got an SJob and ran that query.

**Comment by thammegowda** [comment]
Ah, this is a bug introduced by my recent code. #90 will fix it

**Comment by thammegowda** [comment]
This is fixed in #90, so closing this issue.

Feel free to reopen this or comment on this, if you hit the same issue again.
